# Values to subsitute after cdk deployment
opensearch_endpoint: <your-opensearch-endpoint>
rag_api_endpoint: <your-rag-api-endpoint>
s3_bucket_name: <your-s3-bucket-name>
step_function_arn: <your-step-function-arn>

api_key: <your-api-key>
aws_region: <your-aws-region>

# Ingest
max_concurrency: 3 # This will depend on account limits (vcpu quota / 8)
step_function_timeout_hours: 10 # Depends on amount of data, generally assume an hour of processing per 30 hours of video.
opensearch_index_name: chatbot-vs
opensearch_collection_name: rag-vs

# Chat

file_input_folder: files-to-process/
bucket_image_folder: image_store/
ingest_cache_file: cache_file.txt

# For text file ingestion
chunk_size: "500" # In number of characters, must be a string
overlap: "0.1" # Overlap percentage (0.1 = 10%), must be a string

# The Bedrock Model IDs for each function
model:
  chat: anthropic.claude-3-5-sonnet-20241022-v2:0
  embedding: amazon.titan-embed-text-v2:0
  image_description: anthropic.claude-3-haiku-20240307-v1:0
  video_ingest: anthropic.claude-3-haiku-20240307-v1:0
  audio_ingest: anthropic.claude-3-5-sonnet-20241022-v2:0

chat_prompt: |
  Here are the documents: {documents}

  You are a help desk assistant to Internet ii members and interested people.
  You are to do your best to answer their question in your response.
  Do not start with based on the provided documents.
  If someone wants information for a specific cloud platform, ensure your information is for that platform.

  1. Analyze the given context, which consists of uuid and passage pairs. Each document object contains only a uuid and the text content (passage) of the document.

  2. Using the provided documents, provide the user with a logical sequence of steps to solve their issue.

  3. If the document says canned responses, repeat only what the document says with nothing else.

  4. Read all image descriptions found inside [IMAGE_DESCRIPTION](IMAGE_URL).

  5. If the given image description is helpful to the user return it exactly in this format: ![](IMAGE_URL).
     PROVIDE EVERY USEFUL IMAGE in the area in the text it corresponds with.
     USE EACH IMAGE AT MOST ONE TIME.

  6. Integrate citations naturally in the text by mentioning the source in angel brackets <uuid> after relevant points, line or paragraph. Use only the uuid provided in the documents.

  7. Do not ask the user for more information
